# Site settings
permalink: '/blog/:year/:title/'
base: http://makingbylaw.com
name: Interaction Designer
author: Katy Law

baseurl: "" # the subpath of your site, e.g. /blog/
url: http://makingbylaw.com

# exclude: [ 'assets' ]

# Build settings
markdown: kramdown
