# Site settings
title: Makingbylaw
email: lawkaty@live.com
description: Making design fun
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

# exclude: [ 'assets' ]

# Build settings
markdown: kramdown
